# Numpy 
### numpy用于保存数据和对数据进行数学逻辑等复杂运算的处理
### ndarray：矢量算数运算和复杂广播能力的多维数组
### 对整组数据进行快速运算的标准数学函数*无循环

# ndarray
### 多维性高维数组，
### 同质性所有元素数据类型一致， 
### 高效性连续内存块存储，支持向量化运算

## 多维性


In [2]:
import numpy as np
arr= np.array(5) #创建了0维ndarray数组
print('arr的维度是:'+str(arr.ndim))#打印维度 number of dimensions
print('arr',arr)
print('arr的形状是:'+str(arr.shape))#打印形状 shape（形状） 是指数组的行数和列数。

arr的维度是:0
arr 5
arr的形状是:()


In [3]:
arr= np.array([1,2,3,4,5]) #创建了1维ndarray数组
print('arr的维度是:'+str(arr.ndim))#打印维度 number of dimensions
print('arr',arr)
print('arr的形状是:'+str(arr.shape))#打印形状 shape

arr的维度是:1
arr [1 2 3 4 5]
arr的形状是:(5,)


In [4]:
arr= np.array([[1,2,3,4,5],[6,7,8,9,10]]) #创建了2维ndarray数组
print('arr的维度是:'+str(arr.ndim))#打印维度 number of dimensions
print('arr',arr)
print('arr的形状是:'+str(arr.shape))#打印形状 shape

arr的维度是:2
arr [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
arr的形状是:(2, 5)


## 同质性


In [5]:
arr=np.array([1,'hello',3.14]) #创建了1维ndarray数组，元素类型为object 1被转化为字符串
#不同的数据类型会被转换为相同的数据类型，以便在数组中存储。这个过程称为类型提升（type promotion）。
print('arr的维度是:'+str(arr.ndim))#打印维度 number of dimensions
print('arr',arr)    

arr的维度是:1
arr ['1' 'hello' '3.14']


In [6]:
arr=np.array([1,3.14]) #创建了1维ndarray数组，元素类型为float 1被转化为3.14
print('arr的维度是:'+str(arr.ndim))#打印维度 number of dimensions
print('arr',arr)    

arr的维度是:1
arr [1.   3.14]


# 属 性
### shape 行数与列数
### ndim 维度数量
### size 总元素个数
### dtype 元素类型 （整数浮点数等）
### T 转置 行变列， 列变行
### itemsize 单个元素占用的内存字节数
### flags 内存存储方式


In [7]:
#ndarray的属性
arr=np.array([[1,2,3],[4,5,6]]) #创建了2维ndarray数组
print(arr)
print('数组的形状',arr.shape) #打印数组的形状 shape
print('数组的维度',arr.ndim) #打印数组的维度 number of dimensions
print('数组的元素类型',arr.dtype) #打印数组的元素类型 data type
print('数组的元素个数',arr.size) #打印数组的元素个数 number of elements
print('元素的转置',arr.T) #打印数组的转置 transpose

[[1 2 3]
 [4 5 6]]
数组的形状 (2, 3)
数组的维度 2
数组的元素类型 int64
数组的元素个数 6
元素的转置 [[1 4]
 [2 5]
 [3 6]]



简单记住
多少行 → 就有多少个内层方括号
一行几列 → 内层方括号里有几个元素

# ndarray 的创建
#### 1手动构造小规模数组
#### 2快速初始化固定形状的数组全0 全1
#### 3基于数值范围生成 生成数值序列 用于模拟时间序列 坐标网络
#### 4特殊矩阵生成 数学运算专用（单位矩阵）
#### 5随机数组生成 模拟实验数据 初始化神经网络权重等场景
#### 6高级构造 处理非结构化数据 （文件，字符串）或通过函数生成复杂数组

#### 基础创建

In [8]:
#基础的创建方法
list1=[1,2,3,4,5]
arr= np.array(list1,dtype=np.float64) 
#创建了1维ndarray数组，参数为一个列表,dtype指定了数组元素的数据类型为float64
print(arr)


[1. 2. 3. 4. 5.]


#### copy


In [9]:
#copy
arr1=np.copy(arr) #创建了一个新的ndarray数组arr1，内容与arr相同，但它们是不同的对象shallow copy
print('arr1',arr1)
arr1[0]=10 #修改了arr1的第一个元素
print('修改后arr1',arr1)    
print('修改后arr',arr) #arr没有被修改，说明arr1和arr是不同的对象
#copy是浅复制，arr1和arr指向同一个对象，修改arr1不会修改arr；

arr1 [1. 2. 3. 4. 5.]
修改后arr1 [10.  2.  3.  4.  5.]
修改后arr [1. 2. 3. 4. 5.]


#### 预定义


In [10]:
arr=np.zeros((2,3),dtype=np.int64) #创建了一个2行3列的全零数组
arr1=np.zeros((2,),dtype=np.int64) #创建了一个2个元素的全零数组
print(arr)  
print(arr1)

[[0 0 0]
 [0 0 0]]
[0 0]


In [11]:
arr=np.ones((2,3),dtype=np.int64) #创建了一个2行3列的全一数组
arr1=np.ones((20,),dtype=np.int64) #创建了一个20个元素的全一数组
print(arr)      
print(arr1) 


[[1 1 1]
 [1 1 1]]
[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]


In [12]:
arr=np.empty((4,2),dtype=np.int64) #创建了一个2行3列的空数组，元素值未初始化，可能是随机的
print(arr)


[[                0                 0]
 [                0                 0]
 [                0              1464]
 [31244048832397312      463856467968]]


In [13]:
arr= np.full((3,4),fill_value=7,dtype=np.int64) #创建了一个2行3列的全7数组，元素类型为int64
arr1=np.full((5,),3.14) #创建了一个5个元素的全3.14数组，元素类型为float64
print(arr)
print(arr1)


[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]
[3.14 3.14 3.14 3.14 3.14]


In [14]:

arr1=np.zeros_like(arr) #创建了一个与arr形状和类型相同的全零数组
print(arr1)
arr1=np.ones_like(arr) #创建了一个与arr形状和类型相同的全一数组
print(arr1) 
arr1=np.full_like(arr,fill_value=9) #创建了一个与arr形状和类型相同的全9数组
print(arr1)
arr1=np.empty_like(arr) #创建了一个与arr形状和类型相同的空数组，元素值未初始化，可能是随机的
print(arr1)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
[[9 9 9 9]
 [9 9 9 9]
 [9 9 9 9]]
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


## 数列形式

#### 等差数列

In [15]:
arr=np.arange(1,52,3) #创建了一个包含1到52的等差数列数组start=1,stop=52,step=3
print(arr)


#等间隔左闭右闭
arr=np.linspace(0,100,5,dtype=int) #创建了一个包含0到100的（均分成5份）等间隔数组start=0,stop=100,num=5
print(arr)

[ 1  4  7 10 13 16 19 22 25 28 31 34 37 40 43 46 49]
[  0  25  50  75 100]


##### 指数间隔数组


In [16]:
arr=np.logspace(0,4,5,base=2,dtype=int) #等间隔数组start=0,stop=4,num=5
# 2的0次方到2的4次方的等间隔数组
print(arr)
arr=np.logspace(0,4,5,base=4,dtype=int) #等间隔数组start=0,stop=4,num=5
# 4的0次方到4的4次方的等间隔数组
print(arr)

[ 1  2  4  8 16]
[  1   4  16  64 256]


### 矩阵


In [17]:
#单位矩阵 主对角线的数字为1，其他位置的数字为0
arr=np.eye(4,dtype=np.int64) #创建了一个4行4列的单位矩阵，元素类型为int64
print(arr)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [18]:
#对角矩阵 主对角线上非0的数字其他数字为0 
arr=np.diag([5,2,3,4]) #创建了一个4行4列的对角矩阵，主对角线上的元素为5,2,3,4，其他位置的元素为0
print(arr)  

[[5 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [19]:
#随机数组的生成
arr=np.random.rand(2,3) #创建了一个2行3列的随机数组，元素值在0到1之间均匀分布
print(arr)
#生成指定范围区间的随机浮点数
arr=np.random.uniform(10,20,(2,3)) #创建了一个2行3列的随机数组，元素值在10到20之间均匀分布
print(arr)
#生成指定范围区间的随机整数
arr=np.random.randint(10,20,(2,3)) #创建了一个2行3列的随机数组，元素值在10到20之间均匀分布
print(arr)
#生成随机数列（正态分布）两边小，中间大
arr=np.random.randn(2,3) #创建了一个2行3列的随机数组，元素值服从标准正态分布（均值为0，标准差为1）
print(arr)  
#设计随机种子
np.random.seed(20) #设置随机种子为20，使得每次生成的随机数序列相同
arr=np.random.randint(1,10,(2,5)) #创建了一个2行5列的随机数组，元素值在1到10之间均匀分布
print(arr)

[[0.87193936 0.21292775 0.26155419]
 [0.95235634 0.85679531 0.40096894]]
[[13.66650645 15.98724345 19.82151163]
 [16.01073033 17.4271949  16.82117273]]
[[11 13 12]
 [15 12 17]]
[[ 0.38354388 -1.31313654 -0.45875219]
 [ 1.67547668  0.25464896 -0.16120906]]
[[4 5 7 8 3]
 [1 7 9 6 4]]


### 数据类型

bool 布尔类型

int 整数

float 浮点数

complex 复数


In [20]:
arr=np.array([1,0,1,0],dtype=np.bool) #创建了一个1维ndarray数组，元素类型为bool 1被转化为True，0被转化为False
print(arr)
arr=np.array([1,0,1,0],dtype=np.int64) #创建了一个1维ndarray数组，元素类型为bool 1被转化为True，0被转化为False
print(arr)

[ True False  True False]
[1 0 1 0]


### 索引切片


In [21]:
#整数索引直接访问从0开始
arr=np.random.randint(1,10,20) #创建了一个2行3列的随机数组，元素值在1到10之间均匀分布


In [22]:
print(arr) 
print(arr[0]) #访问第一个元素
print(arr[1]) #访问第二个元素       
print(arr[:])#访问所有元素  (整行或者整列)
print(arr[2:7])#访问第3到第5个元素  (整行或者整列)左闭右开
print(arr[(arr>6)&(arr<8)]) #布尔索引访问所有大于6且小于8的元素
print(arr[slice(2,7,2)]) #start end step 访问第3到第5个元素  (整行或者整列)左闭右开

[1 7 7 1 6 8 6 3 7 4 4 1 7 3 4 2 9 1 3 8]
1
7
[1 7 7 1 6 8 6 3 7 4 4 1 7 3 4 2 9 1 3 8]
[7 1 6 8 6]
[7 7 7 7]
[7 6 6]


In [23]:
arr=np.random.randint(1,100,(4,8)) #创建了一个4行8列的随机数组，元素值在1到10之间均匀分布

In [24]:
print(arr)
print('1',arr[1,3]) #访问第2行第4列的元素，整数索引直接访问从0开始
print('2',arr[: , :]) #访问所有元素  行和列单独控制
print('3',arr[1 , 2:5]) #访问 第2行第3到第5列的元素
print('4',arr[2][arr[2]>33]) #嵌套单行大于33的数
print('5',arr[:,2][arr[:,2]>33]) #嵌套单列大于33的数
print('6',arr[slice(1,4,2),slice(2,6,2)]) #访问第2行到第4行（不包括第4行）和第3列到第6列（不包括第6列）的元素，步长为2



[[76 30 46  7 64 79 25 19]
 [94 34 79 43 95  4 19 71]
 [53 23 15  5 28 76  9  7]
 [27 80 83 79 11 34 86 18]]
1 43
2 [[76 30 46  7 64 79 25 19]
 [94 34 79 43 95  4 19 71]
 [53 23 15  5 28 76  9  7]
 [27 80 83 79 11 34 86 18]]
3 [79 43 95]
4 [53 76]
5 [46 79 83]
6 [[79 95]
 [83 11]]


#### ndarray的运算

In [25]:
a=np.array([1,2,3,9])
b=np.array([4,5,6,8])
print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a**2) 
print(a//2) # 整数除法，结果向下取整
print(a%2) #取模，返回a除以2的余数
c=[1,2,3,4]
d=[5,6,7,8]
print(c+d) #l类似 contact 连接列表的操作



[ 5  7  9 17]
[-3 -3 -3  1]
[ 4 10 18 72]
[0.25  0.4   0.5   1.125]
[ 1  4  9 81]
[0 1 1 4]
[1 0 1 1]
[1, 2, 3, 4, 5, 6, 7, 8]


In [26]:
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
print(a+b)
print(a-b)
#数组与标量之间的算术运算
print(a+3) #广播机制，a的每个元素都加3
print(a*3) #广播机制，a的每个元素都乘3
    

[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[4 5]
 [6 7]]
[[ 3  6]
 [ 9 12]]


#### 广播机制


In [27]:
#1获取形状2是否可以广播，
a=np.array([1,2,3])
b=np.array([[4],[5],[6]])  
print(a+b) #广播机制，a的每个元素都加b的每个元素，结果是一个3行3列的数组 
'''a和b的形状不同,但它们的维度相同(都是1维),因此可以进行广播运算。
广播机制会自动将较小的数组扩展为与较大数组相同的形状，以便进行元素级别的运算。
在这个例子中,a的每个元素都会与b的每个元素进行相加,最终得到一个3行3列的数组。'''

[[5 6 7]
 [6 7 8]
 [7 8 9]]


'a和b的形状不同,但它们的维度相同(都是1维),因此可以进行广播运算。\n广播机制会自动将较小的数组扩展为与较大数组相同的形状，以便进行元素级别的运算。\n在这个例子中,a的每个元素都会与b的每个元素进行相加,最终得到一个3行3列的数组。'

#### 矩阵运算


In [28]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
b=np.array([[5,6,7],[8,9,10],[11,12,13]])
print(a @ b)#矩阵乘法


[[ 54  60  66]
 [126 141 156]
 [198 222 246]]


#### numpy常用函数

#### 基本数学函数

In [29]:
#计算算术平方根
arr=np.array([1,4,9,16,25])
print(np.sqrt(arr)) #计算arr中每个元素的平方根 返回浮点数
#计算指数
arr=np.array([0,1,2,3,4,5])
print(np.exp(arr)) #计算arr中每个元素的指数函数值 返回浮点数
#计算自然对数 lnx
arr=np.array([1,2.71828,7.38906]) #e的0次方，e的1次方，e的2次方
print(np.log(arr)) #计算arr中每个元素的自然对数 返回浮点数
#计算三角函数
arr=np.array([0,np.pi/2,np.pi]) #0度，90度，180度
print(np.sin(arr)) #计算arr中每个元素的正弦值 返回浮点数
print(np.cos(arr)) #计算arr中每个元素的余弦值 返回浮点数
print(np.tan(arr)) #计算arr中每个元素的正切值 返回浮点数
#计算绝对值
arr=np.array([-1,-2,3,-4,5])
print(np.abs(arr)) #计算arr中每个元素的绝对值 返回非负数
#计算a的b次幂
a=np.array([1,2,3,4,5]) 
b=3
print(np.power(a,b)) #计算a中每个元素的b次幂 返回浮点数
#四舍五入
arr=np.array([1.2,2.5,3.51,4.6,5.9])
print(np.round(arr)) #计算arr中每个元素的4舍6入5凑偶 返回整数
#向上取整
arr=np.array([1.2,2.5,3.51,4.6,5.9])
print(np.ceil(arr)) #计算arr中每个元素的向上取整 返回整数
#向下取整   
arr=np.array([1.2,2.5,3.51,4.6,5.9])
print(np.floor(arr)) #计算arr中每个元素的向下取整 返回整数
#检测缺失值
arr=np.array([1,2,np.nan,4,5]) #np.nan表示缺失值 Not a Number
print(np.isnan(arr)) #检测arr中每个元素是否为缺失值 返回布尔数组

[1. 2. 3. 4. 5.]
[  1.           2.71828183   7.3890561   20.08553692  54.59815003
 148.4131591 ]
[0.         0.99999933 2.00000053]
[0.0000000e+00 1.0000000e+00 1.2246468e-16]
[ 1.000000e+00  6.123234e-17 -1.000000e+00]
[ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]
[1 2 3 4 5]
[  1   8  27  64 125]
[1. 2. 4. 5. 6.]
[2. 3. 4. 5. 6.]
[1. 2. 3. 4. 5.]
[False False  True False False]


#### 统计函数

#### 求和 计算平均值 计算中位数 标准差 方差

#### 查找最大值，最小值

#### 计算分位数， 计算累积和， 累计差

In [30]:
np.random.seed(20) #设置随机种子为20，使得每次生成的随机数序列相同
arr=np.random.randint(1,20 ,7)
print(arr)

[ 4 16 10 12  8  3  1]


In [31]:
print(arr)
#求和
print(np.sum(arr)) #计算arr中所有元素的和 返回整数
#求平均值
print(np.mean(arr)) #计算arr中所有元素的平均值 返回浮点数


[ 4 16 10 12  8  3  1]
54
7.714285714285714


In [32]:
print(arr)
#求中位数
# 1     2      3     4
#---------------------------
# 1         2        3

#中位数看中间的 数字
print(np.median(arr)) #计算arr中所有元素的中位数 返回浮点数 
#奇数 排序后中间的数值
# 偶数 排序后中间两个数值的平均值

[ 4 16 10 12  8  3  1]
8.0


In [33]:
print(arr)
#求标准差
print(np.std(arr)) #计算arr中所有元素的标准差 返回浮点数
#标准差越小数据越接近平均值
#求方差
print(np.var(arr)) #计算arr中所有元素的方差 返回浮点数
#方差越小 数据越接近平均值

[ 4 16 10 12  8  3  1]
4.977500397195527
24.77551020408163


In [34]:
print(arr)
#求最大值
print(np.max(arr)) #计算arr中所有元素的最大值 返回整数
#求最小值
print(np.min(arr)) #计算arr中所有元素的最小值 返回整数

[ 4 16 10 12  8  3  1]
16
1


In [35]:
print(arr)
#求分位数
print(np.median(arr)) #计算arr中所有元素的中位数 返回浮点数 
print(np.percentile(arr, 50)) #计算arr中所有元素的50分位数 返回浮点数
print(np.percentile(arr, 20)) #计算arr中所有元素的20分位数 返回浮点数
print(np.percentile(arr, 70)) #计算arr中所有元素的70分位数 返回浮点数
#分位数能够确定数据的分布情况，20分位数表示20%的数据小于等于这个值，70分位数表示70%的数据小于等于这个值。
arr=np.array([1,2,3,4,5])
#求累积和
print(np.cumsum(arr)) #计算arr中所有元素的累积和 返回数组
#求累差
print(np.diff(arr)) #计算arr中所有元素的累差 返回数组
# 累计积
print(np.cumprod(arr)) #计算arr中所有元素的累计积 返回数组


[ 4 16 10 12  8  3  1]
8.0
8.0
3.2
10.399999999999999
[ 1  3  6 10 15]
[1 1 1 1]
[  1   2   6  24 120]


#### 比较函数

#### 比较是否大于，小于 ，等于

#### 逻辑与，或，非， 检查数组是否有一个True是否所有都为true 自定义操作


In [36]:

arr=np.array([1,2,3,4,5])
#是否大于
print(np.greater(arr ,4)) #计算arr中每个元素是否大于4 返回布尔数组
#是否小于
print(np.less(arr ,4)) #计算arr中每个元素是否小于4 返回布尔数组
#是否等于
print(np.equal(arr ,4)) #计算arr中每个元素是否等于4 返回布尔数组   
#是否不等于
print(np.not_equal(arr ,4)) #计算arr中每个元素是否不等于4 返回布尔数组
#是否大于等于
print(np.greater_equal(arr ,4)) #计算arr中每个元素是否大于等于4 返回布尔数组
#是否小于等于
print(np.less_equal(arr ,4)) #计算arr中每个元素是否小于等于4 返回布尔数组
#逻辑与
print(np.logical_and(arr>2,arr<5)) #计算arr中每个元素是否大于2且小于5 返回布尔数组
print(np.logical_and([1,0],[1,1])) #计算两个布尔数组的逻辑与 返回布尔数组
#逻辑或
print(np.logical_or(arr<2,arr>4)) #计算arr中每个元素是否小于2或大于4 返回布尔数组   
print(np.logical_or([1,0],[1,1])) #计算两个布尔数组的逻辑或 返回布尔数组
#逻辑非
print(np.logical_not(arr>2)) #计算arr中每个元素是否不大于2 返回布尔数组
print(np.logical_not([1,0])) #计算两个布尔数组的逻辑非 返回布尔数组


[False False False False  True]
[ True  True  True False False]
[False False False  True False]
[ True  True  True False  True]
[False False False  True  True]
[ True  True  True  True False]
[False False  True  True False]
[ True False]
[ True False False False  True]
[ True  True]
[ True  True False False False]
[False  True]


In [37]:
#检查元素是否有一个元素为true
print(np.any([0,0,0,0,1])) #检查arr中是否有一个元素大于3 返回布尔值
#检查元素是否所有元素为true
print(np.all([1,1,1,1,1])) #检查arr中是否所有元素都大于0 返回布尔值

True
True


### 自定义函数

In [38]:
#自定义函数😊
arr=np.array([1,2,3,4,5])
#np.where(condition,x,y)参数： 条件 符合输出 不符合输出
print(np.where(arr>3,arr*2,arr/2)) #计算arr中每个元素是否大于3，
#如果大于3返回该元素的两倍，否则返回该元素的一半 返回数组

print(np.where(arr>3,1,0))  
score=np.random.randint(0,101,10)
print(score)
print(np.where(score>=60,'及格','不及格')) 

#嵌套
print(np.where(score<60,'不及格',np.where(score<80,'及格','优秀')))

# np.select(condlist,choicelist,default=0)参数： 条件列表 选择列表 默认值
print(np.select([score<20,score<40,score<60,score<80,score<=100],[ '糟糕','较差','挂科','及格','优秀'],'未知'))

[ 0.5  1.   1.5  8.  10. ]
[0 0 0 1 1]
[40 85 90 26 83 16 62 16  7 98]
['不及格' '及格' '及格' '不及格' '及格' '不及格' '及格' '不及格' '不及格' '及格']
['不及格' '优秀' '优秀' '不及格' '优秀' '不及格' '及格' '不及格' '不及格' '优秀']
['挂科' '优秀' '优秀' '较差' '优秀' '糟糕' '及格' '糟糕' '糟糕' '优秀']


#### 排序函数

In [44]:
#排序
np.random.seed(20) #设置随机种子为20，使得每次生成的随机数序列相同
arr=np.random.randint(1,100,20) #创建了一个20个元素的随机数组，元素值在1到100之间均匀分布
print(arr)
#arr.sort() #对arr中的元素进行排序，默认升序排序，改变了原数组

print(np.sort(arr)) #对arr中的元素进行排序，默认升序排序，返回一个新的数组，原数组不变
print(np.argsort(arr))
print(arr)

[91 16 96 29 91 10 21 76 23 72 35 97 41 86 91 27 84 17 63 17]
[10 16 17 17 21 23 27 29 35 41 63 72 76 84 86 91 91 91 96 97]
[ 5  1 19 17  6  8 15  3 10 12 18  9  7 16 13  0  4 14  2 11]
[91 16 96 29 91 10 21 76 23 72 35 97 41 86 91 27 84 17 63 17]


### 去重

In [46]:
#去重
print(np.unique(arr)) #对arr中的元素进行去重,也会排序，返回一个新的数组，原数组不变

[10 16 17 21 23 27 29 35 41 63 72 76 84 86 91 96 97]


## 数组的拼接

In [48]:
#数组拼接
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
print(arr1+arr2)
print(np.concatenate((arr1,arr2))) #将arr1和arr2拼接成一个新的数组 返回数组
print(np.hstack((arr1,arr2))) #将arr1和arr2水平拼接成一个新的数组 返回数组
print(np.vstack((arr1,arr2))) #将arr1和arr2垂直拼接成一个新的数组 返回数组

[5 7 9]
[1 2 3 4 5 6]
[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


In [54]:
#数组的分割
print(arr)
print(np.split(arr, 4)) #将arr分割成4个子数组 返回一个包含4个子数组的列表 必须能等分
print(np.split(arr, [6,12,18])) #将arr分割成4个子数组 返回一个包含4个子数组的列表 不要求能等分
#调整数组的形状
print(np.reshape(arr, (4,5))) #将arr调整为4行5列的数组 返回数组
print(np.reshape(arr, (5,4))) #将arr调整为5行4列

[91 16 96 29 91 10 21 76 23 72 35 97 41 86 91 27 84 17 63 17]
[array([91, 16, 96, 29, 91], dtype=int32), array([10, 21, 76, 23, 72], dtype=int32), array([35, 97, 41, 86, 91], dtype=int32), array([27, 84, 17, 63, 17], dtype=int32)]
[array([91, 16, 96, 29, 91, 10], dtype=int32), array([21, 76, 23, 72, 35, 97], dtype=int32), array([41, 86, 91, 27, 84, 17], dtype=int32), array([63, 17], dtype=int32)]
[[91 16 96 29 91]
 [10 21 76 23 72]
 [35 97 41 86 91]
 [27 84 17 63 17]]
[[91 16 96 29]
 [91 10 21 76]
 [23 72 35 97]
 [41 86 91 27]
 [84 17 63 17]]


In [62]:
import numpy as np
temps=np.array([28,30,29,31,32,30,29])
print(temps)
print('平均温度:','%.3f' % np.mean(temps),'度') #计算temps中所有元素的平均值 返回浮点数
print('最高温度:',np.max(temps),'度') #计算temps中所有元素的最大值 返回整数
print('最低温度:',np.min(temps),'度') #计算temps中所有元素的最小值 返回整数
print('温度范围:',np.ptp(temps),'度') #计算temps中所有元素的范围（最大值与最小值之差） 返回整数
print('气温超过30度的天数:',np.sum(temps>30),'天') #计算temps中大于30的元素个数 返回整数
print('分别是:',temps[temps>30]) #计算temps中大于30的元素 返回数组  
print('气温超过30度的天数:',np.count_nonzero(temps>30),'天') #计算temps中大于30的元素个数 返回整数

[28 30 29 31 32 30 29]
平均温度: 29.857 度
最高温度: 32 度
最低温度: 28 度
温度范围: 4 度
气温超过30度的天数: 2 天
分别是: [31 32]
气温超过30度的天数: 2 天


In [86]:
score=np.array([85,90,78,92,88])
print(score)
print('平均分:','%.3f' % np.mean(score)) #计算score中所有元素的平均值 返回浮点数
print('中位数:',np.median(score)) #计算score中所有元素的中位数 返回浮点数
print('标准差:',round(np.std(score), 3)) #计算score中所有元素的标准差 返回浮点数
print('成绩转换为百分制:', (score/100*10)) #将score中所有元素转换为十分制 返回数组

[85 90 78 92 88]
平均分: 86.600
中位数: 88.0
标准差: 4.883
成绩转换为百分制: [8.5 9.  7.8 9.2 8.8]


In [69]:
A=np.array([[1,2],[3,4]])
B=np.array([[5,6],[7,8]])
print(A+B)
print(A*B)
print(A @ B)#矩阵乘法

[[ 6  8]
 [10 12]]
[[ 5 12]
 [21 32]]
[[19 22]
 [43 50]]


In [79]:
np.random.seed(20) #设置随机种子为20，使得每次生成的随机数序列相同
arr=np.random.randint(0,10,size=(3,4))
print(arr)
print("每行的最大值:",np.max(arr,axis=1)) #计算arr中每行的最大值 返回数组
print("每列的最大值:",np.min(arr,axis=0)) #计算arr中每列的最大值 返回数组axis=0 
#axis=0表示沿着列的方向计算，即每列的最大值；axis=1表示沿着行的方向计算，即每行的最大值。
print(np.where(arr%2==1,-1,arr)) #将arr中所有奇数换为1 返回数组
print(arr[arr%2==1]) #将arr中所有奇数换为1 返回数组

[[3 9 4 6]
 [7 2 0 6]
 [8 5 3 0]]
每行的最大值: [9 7 8]
每列的最大值: [3 2 0 0]
[[-1 -1  4  6]
 [-1  2  0  6]
 [ 8 -1 -1  0]]
[3 9 7 5 3]


In [91]:

arr=np.arange(1,13)
print(arr)
arr=np.reshape(arr,(3,4)) #将arr调整为3行4列的数组 返回数组
print(arr)
print('每行的和:', np.sum(arr, axis=1)) #计算arr中每行的和 返回数组
print('每列的平均值:', np.mean(arr, axis=0)) #计算arr中每列的平均值 返回数组
arr=np.reshape(arr,(12)) #将arr调整为4行3列的数组 返回数组
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
每行的和: [10 26 42]
每列的平均值: [5. 6. 7. 8.]
[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [98]:
np.random.seed(20) #设置随机种子为20，使得每次生成的随机数序列相同
arr =np.random.randint(1,20,(5,5))
print(arr)
print(arr[arr>10])
print(np.where(arr>10, 0, arr)) #将arr中所有大于10的元素换为-1 返回数组

[[ 4 16 10 12  8]
 [ 3  1  9 17  7]
 [ 7 17 10  6  8]
 [ 6  3  7 14 12]
 [ 4 11 12 14 15]]
[16 12 17 17 14 12 11 12 14 15]
[[ 4  0 10  0  8]
 [ 3  1  9  0  7]
 [ 7  0 10  6  8]
 [ 6  3  7  0  0]
 [ 4  0  0  0  0]]


In [100]:
money=np.array([120,135,110,125,130,140])
print('总和:', np.sum(money)) #计算money中所有元素的和 返回整数
print('平均值:', np.mean(money)) #计算money中所有元素的平均值 返回浮点数
print('方差:', np.var(money)) #计算money中所有元素的方差 返回浮点数 
print('最高的月份:', np.argmax(money)+1) #计算money中所有元素的最大值的索引 返回整数
print('最低的月份:', np.argmin(money)+1 ) #计算money中所有元素的最小值的索引 返回整数  

总和: 760
平均值: 126.66666666666667
方差: 97.22222222222223
最高的月份: 6
最低的月份: 3


In [102]:
A=np.array([1,2,3,4,5])
B=np.array([5,4,3,2,1])
print(np.concatenate((A,B)))
print(np.vstack((A,B)))

[1 2 3 4 5 5 4 3 2 1]
[[1 2 3 4 5]
 [5 4 3 2 1]]


In [107]:
A=np.array([2,1,2,3,1,4,3])
print(np.unique(A)) #对A中的元素进行去重,也会排序，返回一个新的数组，原数组不变
u_arr, counts = np.unique(A, return_counts=True)
#对A中的元素进行去重,也会排序，返回一个新的数组和每个唯一值出现的次数，原数组不变
print("唯一值:", u_arr)
print("出现次数:", counts)

[1 2 3 4]
唯一值: [1 2 3 4]
出现次数: [2 2 2 1]


In [115]:
money=np.array([20,25,22,30,28])
price=np.array([15,18,16,22,20])
profit=money-price
print(profit)
print('总利润:', np.sum(profit)) #计算profit中所有元素的和 返回整数
print('平均利润:', np.mean(profit)) #计算profit中所有元素的平均值
print('利润的标准差:', np.std(profit)) #计算profit中所有元素的标准差 返回浮点数
print('利润最高的天数:', len(profit[profit==np.max(profit)])) #计算profit中所有元素的最大值的索引 返回整数
print('利润最高的天数:', np.sum(profit==np.max(profit))) #计算profit中所有元素的最大值的索引 返回整数

[5 7 6 8 8]
总利润: 34
平均利润: 6.8
利润的标准差: 1.16619037896906
利润最高的天数: 2
利润最高的天数: 2
