# Numpy 
### numpy用于保存数据和对数据进行数学逻辑等复杂运算的处理
### ndarray：矢量算数运算和复杂广播能力的多维数组
### 对整组数据进行快速运算的标准数学函数*无循环

# ndarray
### 多维性高维数组，
### 同质性所有元素数据类型一致， 
### 高效性连续内存块存储，支持向量化运算

## 多维性


In [12]:
import numpy as np
arr= np.array(5) #创建了0维ndarray数组
print('arr的维度是:'+str(arr.ndim))#打印维度 number of dimensions
print('arr',arr)
print('arr的形状是:'+str(arr.shape))#打印形状 shape（形状） 是指数组的行数和列数。

arr的维度是:0
arr 5
arr的形状是:()


In [13]:
arr= np.array([1,2,3,4,5]) #创建了1维ndarray数组
print('arr的维度是:'+str(arr.ndim))#打印维度 number of dimensions
print('arr',arr)
print('arr的形状是:'+str(arr.shape))#打印形状 shape

arr的维度是:1
arr [1 2 3 4 5]
arr的形状是:(5,)


In [16]:
arr= np.array([[1,2,3,4,5],[6,7,8,9,10]]) #创建了2维ndarray数组
print('arr的维度是:'+str(arr.ndim))#打印维度 number of dimensions
print('arr',arr)
print('arr的形状是:'+str(arr.shape))#打印形状 shape

arr的维度是:2
arr [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
arr的形状是:(2, 5)


## 同质性


In [17]:
arr=np.array([1,'hello',3.14]) #创建了1维ndarray数组，元素类型为object 1被转化为字符串
#不同的数据类型会被转换为相同的数据类型，以便在数组中存储。这个过程称为类型提升（type promotion）。
print('arr的维度是:'+str(arr.ndim))#打印维度 number of dimensions
print('arr',arr)    

arr的维度是:1
arr ['1' 'hello' '3.14']


In [18]:
arr=np.array([1,3.14]) #创建了1维ndarray数组，元素类型为float 1被转化为3.14
print('arr的维度是:'+str(arr.ndim))#打印维度 number of dimensions
print('arr',arr)    

arr的维度是:1
arr [1.   3.14]


# 属 性
### shape 行数与列数
### ndim 维度数量
### size 总元素个数
### dtype 元素类型 （整数浮点数等）
### T 转置 行变列， 列变行
### itemsize 单个元素占用的内存字节数
### flags 内存存储方式


In [22]:
#ndarray的属性
arr=np.array([[1,2,3],[4,5,6]]) #创建了2维ndarray数组
print(arr)
print('数组的形状',arr.shape) #打印数组的形状 shape
print('数组的维度',arr.ndim) #打印数组的维度 number of dimensions
print('数组的元素类型',arr.dtype) #打印数组的元素类型 data type
print('数组的元素个数',arr.size) #打印数组的元素个数 number of elements
print('元素的转置',arr.T) #打印数组的转置 transpose

[[1 2 3]
 [4 5 6]]
数组的形状 (2, 3)
数组的维度 2
数组的元素类型 int64
数组的元素个数 6
元素的转置 [[1 4]
 [2 5]
 [3 6]]



简单记住
多少行 → 就有多少个内层方括号
一行几列 → 内层方括号里有几个元素

# ndarray 的创建
#### 1手动构造小规模数组
#### 2快速初始化固定形状的数组全0 全1
#### 3基于数值范围生成 生成数值序列 用于模拟时间序列 坐标网络
#### 4特殊矩阵生成 数学运算专用（单位矩阵）
#### 5随机数组生成 模拟实验数据 初始化神经网络权重等场景
#### 6高级构造 处理非结构化数据 （文件，字符串）或通过函数生成复杂数组

#### 基础创建

In [26]:
#基础的创建方法
list1=[1,2,3,4,5]
arr= np.array(list1,dtype=np.float64) 
#创建了1维ndarray数组，参数为一个列表,dtype指定了数组元素的数据类型为float64
print(arr)


[1. 2. 3. 4. 5.]


#### copy


In [ ]:
#copy
arr1=np.copy(arr) #创建了一个新的ndarray数组arr1，内容与arr相同，但它们是不同的对象shallow copy
print('arr1',arr1)
arr1[0]=10 #修改了arr1的第一个元素
print('修改后arr1',arr1)    
print('修改后arr',arr) #arr没有被修改，说明arr1和arr是不同的对象
#copy是浅复制，arr1和arr指向同一个对象，修改arr1不会修改arr；

arr1 [1. 2. 3. 4. 5.]
修改后arr1 [10.  2.  3.  4.  5.]
修改后arr [1. 2. 3. 4. 5.]


#### 预定义


In [ ]:
arr=np.zeros((2,3),dtype=np.int64) #创建了一个2行3列的全零数组
arr1=np.zeros((2,),dtype=np.int64) #创建了一个2个元素的全零数组
print(arr)  
print(arr1)

[[0 0 0]
 [0 0 0]]
[0 0]


In [ ]:
arr=np.ones((2,3),dtype=np.int64) #创建了一个2行3列的全一数组
arr1=np.ones((20,),dtype=np.int64) #创建了一个20个元素的全一数组
print(arr)      
print(arr1) 


[[1 1 1]
 [1 1 1]]
[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]


In [51]:
arr=np.empty((4,2),dtype=np.int64) #创建了一个2行3列的空数组，元素值未初始化，可能是随机的
print(arr)


[[25895968444448860 23925768161198147]
 [32370111954616435 30399731283001436]
 [31525476570497132 32651513914720368]
 [31244048838426721      463862825059]]


In [60]:
arr= np.full((3,4),fill_value=7,dtype=np.int64) #创建了一个2行3列的全7数组，元素类型为int64
arr1=np.full((5,),3.14) #创建了一个5个元素的全3.14数组，元素类型为float64
print(arr)
print(arr1)


[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]
[3.14 3.14 3.14 3.14 3.14]


In [61]:

arr1=np.zeros_like(arr) #创建了一个与arr形状和类型相同的全零数组
print(arr1)
arr1=np.ones_like(arr) #创建了一个与arr形状和类型相同的全一数组
print(arr1) 
arr1=np.full_like(arr,fill_value=9) #创建了一个与arr形状和类型相同的全9数组
print(arr1)
arr1=np.empty_like(arr) #创建了一个与arr形状和类型相同的空数组，元素值未初始化，可能是随机的
print(arr1)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
[[9 9 9 9]
 [9 9 9 9]
 [9 9 9 9]]
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
