# Numpy 
### numpy用于保存数据和对数据进行数学逻辑等复杂运算的处理
### ndarray：矢量算数运算和复杂广播能力的多维数组
### 对整组数据进行快速运算的标准数学函数*无循环

# ndarray
### 多维性高维数组，
### 同质性所有元素数据类型一致， 
### 高效性连续内存块存储，支持向量化运算

## 多维性


In [2]:
import numpy as np
arr= np.array(5) #创建了0维ndarray数组
print('arr的维度是:'+str(arr.ndim))#打印维度 number of dimensions
print('arr',arr)
print('arr的形状是:'+str(arr.shape))#打印形状 shape（形状） 是指数组的行数和列数。

arr的维度是:0
arr 5
arr的形状是:()


In [3]:
arr= np.array([1,2,3,4,5]) #创建了1维ndarray数组
print('arr的维度是:'+str(arr.ndim))#打印维度 number of dimensions
print('arr',arr)
print('arr的形状是:'+str(arr.shape))#打印形状 shape

arr的维度是:1
arr [1 2 3 4 5]
arr的形状是:(5,)


In [4]:
arr= np.array([[1,2,3,4,5],[6,7,8,9,10]]) #创建了2维ndarray数组
print('arr的维度是:'+str(arr.ndim))#打印维度 number of dimensions
print('arr',arr)
print('arr的形状是:'+str(arr.shape))#打印形状 shape

arr的维度是:2
arr [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
arr的形状是:(2, 5)


## 同质性


In [5]:
arr=np.array([1,'hello',3.14]) #创建了1维ndarray数组，元素类型为object 1被转化为字符串
#不同的数据类型会被转换为相同的数据类型，以便在数组中存储。这个过程称为类型提升（type promotion）。
print('arr的维度是:'+str(arr.ndim))#打印维度 number of dimensions
print('arr',arr)    

arr的维度是:1
arr ['1' 'hello' '3.14']


In [6]:
arr=np.array([1,3.14]) #创建了1维ndarray数组，元素类型为float 1被转化为3.14
print('arr的维度是:'+str(arr.ndim))#打印维度 number of dimensions
print('arr',arr)    

arr的维度是:1
arr [1.   3.14]


# 属 性
### shape 行数与列数
### ndim 维度数量
### size 总元素个数
### dtype 元素类型 （整数浮点数等）
### T 转置 行变列， 列变行
### itemsize 单个元素占用的内存字节数
### flags 内存存储方式


In [7]:
#ndarray的属性
arr=np.array([[1,2,3],[4,5,6]]) #创建了2维ndarray数组
print(arr)
print('数组的形状',arr.shape) #打印数组的形状 shape
print('数组的维度',arr.ndim) #打印数组的维度 number of dimensions
print('数组的元素类型',arr.dtype) #打印数组的元素类型 data type
print('数组的元素个数',arr.size) #打印数组的元素个数 number of elements
print('元素的转置',arr.T) #打印数组的转置 transpose

[[1 2 3]
 [4 5 6]]
数组的形状 (2, 3)
数组的维度 2
数组的元素类型 int64
数组的元素个数 6
元素的转置 [[1 4]
 [2 5]
 [3 6]]



简单记住
多少行 → 就有多少个内层方括号
一行几列 → 内层方括号里有几个元素

# ndarray 的创建
#### 1手动构造小规模数组
#### 2快速初始化固定形状的数组全0 全1
#### 3基于数值范围生成 生成数值序列 用于模拟时间序列 坐标网络
#### 4特殊矩阵生成 数学运算专用（单位矩阵）
#### 5随机数组生成 模拟实验数据 初始化神经网络权重等场景
#### 6高级构造 处理非结构化数据 （文件，字符串）或通过函数生成复杂数组

#### 基础创建

In [8]:
#基础的创建方法
list1=[1,2,3,4,5]
arr= np.array(list1,dtype=np.float64) 
#创建了1维ndarray数组，参数为一个列表,dtype指定了数组元素的数据类型为float64
print(arr)


[1. 2. 3. 4. 5.]


#### copy


In [9]:
#copy
arr1=np.copy(arr) #创建了一个新的ndarray数组arr1，内容与arr相同，但它们是不同的对象shallow copy
print('arr1',arr1)
arr1[0]=10 #修改了arr1的第一个元素
print('修改后arr1',arr1)    
print('修改后arr',arr) #arr没有被修改，说明arr1和arr是不同的对象
#copy是浅复制，arr1和arr指向同一个对象，修改arr1不会修改arr；

arr1 [1. 2. 3. 4. 5.]
修改后arr1 [10.  2.  3.  4.  5.]
修改后arr [1. 2. 3. 4. 5.]


#### 预定义


In [10]:
arr=np.zeros((2,3),dtype=np.int64) #创建了一个2行3列的全零数组
arr1=np.zeros((2,),dtype=np.int64) #创建了一个2个元素的全零数组
print(arr)  
print(arr1)

[[0 0 0]
 [0 0 0]]
[0 0]


In [11]:
arr=np.ones((2,3),dtype=np.int64) #创建了一个2行3列的全一数组
arr1=np.ones((20,),dtype=np.int64) #创建了一个20个元素的全一数组
print(arr)      
print(arr1) 


[[1 1 1]
 [1 1 1]]
[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]


In [12]:
arr=np.empty((4,2),dtype=np.int64) #创建了一个2行3列的空数组，元素值未初始化，可能是随机的
print(arr)


[[                  0                   0]
 [                  0                   0]
 [                  0                1568]
 [8389186995951239168 7311146992019701760]]


In [13]:
arr= np.full((3,4),fill_value=7,dtype=np.int64) #创建了一个2行3列的全7数组，元素类型为int64
arr1=np.full((5,),3.14) #创建了一个5个元素的全3.14数组，元素类型为float64
print(arr)
print(arr1)


[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]
[3.14 3.14 3.14 3.14 3.14]


In [14]:

arr1=np.zeros_like(arr) #创建了一个与arr形状和类型相同的全零数组
print(arr1)
arr1=np.ones_like(arr) #创建了一个与arr形状和类型相同的全一数组
print(arr1) 
arr1=np.full_like(arr,fill_value=9) #创建了一个与arr形状和类型相同的全9数组
print(arr1)
arr1=np.empty_like(arr) #创建了一个与arr形状和类型相同的空数组，元素值未初始化，可能是随机的
print(arr1)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
[[9 9 9 9]
 [9 9 9 9]
 [9 9 9 9]]
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


## 数列形式

#### 等差数列

In [15]:
arr=np.arange(1,52,3) #创建了一个包含1到52的等差数列数组start=1,stop=52,step=3
print(arr)


#等间隔左闭右闭
arr=np.linspace(0,100,5,dtype=int) #创建了一个包含0到100的（均分成5份）等间隔数组start=0,stop=100,num=5
print(arr)

[ 1  4  7 10 13 16 19 22 25 28 31 34 37 40 43 46 49]
[  0  25  50  75 100]


##### 指数间隔数组


In [16]:
arr=np.logspace(0,4,5,base=2,dtype=int) #等间隔数组start=0,stop=4,num=5
# 2的0次方到2的4次方的等间隔数组
print(arr)
arr=np.logspace(0,4,5,base=4,dtype=int) #等间隔数组start=0,stop=4,num=5
# 4的0次方到4的4次方的等间隔数组
print(arr)

[ 1  2  4  8 16]
[  1   4  16  64 256]


### 矩阵


In [17]:
#单位矩阵 主对角线的数字为1，其他位置的数字为0
arr=np.eye(4,dtype=np.int64) #创建了一个4行4列的单位矩阵，元素类型为int64
print(arr)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [18]:
#对角矩阵 主对角线上非0的数字其他数字为0 
arr=np.diag([5,2,3,4]) #创建了一个4行4列的对角矩阵，主对角线上的元素为5,2,3,4，其他位置的元素为0
print(arr)  

[[5 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [22]:
#随机数组的生成
arr=np.random.rand(2,3) #创建了一个2行3列的随机数组，元素值在0到1之间均匀分布
print(arr)
#生成指定范围区间的随机浮点数
arr=np.random.uniform(10,20,(2,3)) #创建了一个2行3列的随机数组，元素值在10到20之间均匀分布
print(arr)
#生成指定范围区间的随机整数
arr=np.random.randint(10,20,(2,3)) #创建了一个2行3列的随机数组，元素值在10到20之间均匀分布
print(arr)
#生成随机数列（正态分布）两边小，中间大
arr=np.random.randn(2,3) #创建了一个2行3列的随机数组，元素值服从标准正态分布（均值为0，标准差为1）
print(arr)  
#设计随机种子
np.random.seed(20) #设置随机种子为20，使得每次生成的随机数序列相同
arr=np.random.randint(1,10,(2,5)) #创建了一个2行5列的随机数组，元素值在1到10之间均匀分布
print(arr)

[[1.42866818e-01 6.50888473e-01 5.64115790e-02]
 [7.21998772e-01 9.38552709e-01 7.78765841e-04]]
[[19.92211559 16.1748151  16.1165316 ]
 [10.07066305 10.23062425 15.2477466 ]]
[[19 12 16]
 [13 18 12]]
[[ 0.41701111  0.83246186 -0.29339915]
 [-0.02983857  0.09512578  0.66465434]]
[[4 5 7 8 3]
 [1 7 9 6 4]]


### 数据类型

bool 布尔类型

int 整数

float 浮点数

complex 复数


In [26]:
arr=np.array([1,0,1,0],dtype=np.bool) #创建了一个1维ndarray数组，元素类型为bool 1被转化为True，0被转化为False
print(arr)
arr=np.array([1,0,1,0],dtype=np.int64) #创建了一个1维ndarray数组，元素类型为bool 1被转化为True，0被转化为False
print(arr)

[ True False  True False]
[1 0 1 0]


### 索引切片


In [ ]:
#整数索引直接访问从0开始
arr=np.random.randint(1,10,20) #创建了一个2行3列的随机数组，元素值在1到10之间均匀分布


In [53]:
print(arr) 
print(arr[0]) #访问第一个元素
print(arr[1]) #访问第二个元素       
print(arr[:])#访问所有元素  (整行或者整列)
print(arr[2:7])#访问第3到第5个元素  (整行或者整列)左闭右开
print(arr[(arr>6)&(arr<8)]) #布尔索引访问所有大于6且小于8的元素
print(arr[slice(2,7,2)]) #start end step 访问第3到第5个元素  (整行或者整列)左闭右开

[8 9 1 2 5 8 1 5 7 3 2 1 6 8 1 5 8 8 5 2]
8
9
[8 9 1 2 5 8 1 5 7 3 2 1 6 8 1 5 8 8 5 2]
[1 2 5 8 1]
[7]
[1 5 1]


In [59]:
arr=np.random.randint(1,100,(4,8)) #创建了一个4行8列的随机数组，元素值在1到10之间均匀分布

In [77]:
print(arr)
print('1',arr[1,3]) #访问第2行第4列的元素，整数索引直接访问从0开始
print('2',arr[: , :]) #访问所有元素  行和列单独控制
print('3',arr[1 , 2:5]) #访问 第2行第3到第5列的元素
print('4',arr[2][arr[2]>33]) #嵌套单行大于33的数
print('5',arr[:,2][arr[:,2]>33]) #嵌套单列大于33的数
print('6',arr[slice(1,4,2),slice(2,6,2)]) #访问第2行到第4行（不包括第4行）和第3列到第6列（不包括第6列）的元素，步长为2



[[10 67 82 33 52 20 93 40]
 [77 56 73 79  6 49  5 81]
 [63 35 52 27 20 56 86 23]
 [ 5 51 13 96 85 51 90 69]]
1 79
2 [[10 67 82 33 52 20 93 40]
 [77 56 73 79  6 49  5 81]
 [63 35 52 27 20 56 86 23]
 [ 5 51 13 96 85 51 90 69]]
3 [73 79  6]
4 [63 35 52 56 86]
5 [82 73 52]
6 [[73  6]
 [13 85]]


#### ndarray的运算

In [89]:
a=np.array([1,2,3,9])
b=np.array([4,5,6,8])
print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a**2) 
print(a//2) # 整数除法，结果向下取整
print(a%2) #取模，返回a除以2的余数
c=[1,2,3,4]
d=[5,6,7,8]
print(c+d) #l类似 contact 连接列表的操作



[ 5  7  9 17]
[-3 -3 -3  1]
[ 4 10 18 72]
[0.25  0.4   0.5   1.125]
[ 1  4  9 81]
[0 1 1 4]
[1 0 1 1]
[1, 2, 3, 4, 5, 6, 7, 8]


In [ ]:
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
print(a+b)
print(a-b)
#数组与标量之间的算术运算
print(a+3) #广播机制，a的每个元素都加3
print(a*3) #广播机制，a的每个元素都乘3
    

[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[4 5]
 [6 7]]
[[ 3  6]
 [ 9 12]]
